name: Node.js CI/CD test

on:
  push:
    branches: test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    # - run: npm run test:unit
    # - run: npm run test:e2e
    # TODO currently not run test since we have not worked on it
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TARGET_DIR_TEST: ${{ secrets.TARGET_DIR_TEST }}
      run: |
        SSH_PATH="$HOME/.ssh"
        mkdir "$SSH_PATH"
        echo "$SSH_PRIVATE_KEY" > "$SSH_PATH/id_rsa"
        chmod 600 "$SSH_PATH/id_rsa"
        ssh-keyscan yusanshi.com >> "$SSH_PATH/known_hosts"
        rsync -az --delete -e "ssh -i $SSH_PATH/id_rsa" ./dist/ "github@yusanshi.com:$TARGET_DIR_TEST"